### ISSUE TITLE
Problem after updating to 1.2.0 version

### ISSUE THREAD

**Issue by netkata-dev** [composer/ca-bundle#44]
Weve updated this package to version 1.2.0 (it is in dependencies in bugnsag package that we use) after that we get error about. "open_basedir restriction in effect" in path "/etc/pki/tls/certs/ca-bundle.crt". 

We use CentOS with CloudLinux and we did not have this problem in previous version of package (1.1.4) is that behavior expected - throwing exception when cannot get to the file? 

If possible we would like not to change open_basedir path.

Thanks in advance.

**Comment by DevelopersDrop** [comment]
We are facing the same problem after upgrading to version 1.2.0:

{"0":"Warning: is_file(): open_basedir restriction in effect. File(/etc/pki/tls/cert.pem) is not within the allowed path(s): (/data/var/www/vhosts/***/) in /data/var/www/vhosts/***/vendor/composer/ca-bundle/src/CaBundle.php on line 309","1":"<pre>#1 is_file() called at [vendor/composer/ca-bundle/src/CaBundle.php:309]

Downgrading to version 1.1.4 everything is back to work.

**Comment by lfritsche** [comment]
Same here: `open_basedir restriction in effect. File(/usr/lib/ssl/certs) is not within the allowed path(s)`

**Comment by exussum12** [comment]
I will get a pr up for this tomorrow

**Comment by exussum12** [comment]
In fact or is up now #45

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/ca-bundle/pull/45 - I'll tag 1.2.1 in a minute

**Comment by dwightwatson** [comment]
I'm still experiencing certificate related issues (through cURL) on both 1.2.0 and 1.2.1, which are resolved by downgrading back to 1.1.4.

```
cURL error (77): error setting certificate verify locations:
  CAfile: /usr/lib/ssl/certs
  CApath: /etc/ssl/certs
```

**Comment by exussum12** [comment]
Do both of them exist ? What does cat  /usr/lib/ssl/certs show ?

**Comment by lfjeff** [comment]
I'm also running ca-bundle 1.2.1 on Ubuntu 16.04 and am experiencing the same cURL error(77)

**Comment by Seldaek** [comment]
@dwightwatson @lfjeff please try again with 1.2.2 to see if it helps..

**Comment by dwightwatson** [comment]
I've tried again on 1.2.2 but I still appear to have the same issue.

**Comment by exussum12** [comment]
In that case do we remove the openssl default location ? My system defaults to that rather than the paths hard coded ?

Either that or move the openssl location to be below the hard coded paths but before the final fall back of the bundle ?

**Comment by exussum12** [comment]
It looks like the default dir is being used, and the default file is not being overwritten. Previously the default file would have been set.

For some reason the file suggested by openssl_get_cert_locations doesnt actually exist (even on my OS this doesnt exist, the default before hand is used and works kinda by accident.

I think the openssl_get_cert_locations command needs to be removed if it cant be trusted to give a correct path to file ? I have opened a PR if everyone agress to ignore its input and just look it up the classic way

**Comment by exussum12** [comment]
https://github.com/openssl/openssl/issues/4708 could be related.

**Comment by wa1kb0y** [comment]
Same error with 1.2.2 on Ubuntu 16.04
```
cURL error (77): error setting certificate verify locations:
  CAfile: /usr/lib/ssl/certs
  CApath: /etc/ssl/certs
```

Downgrading to 1.1.4 helped me

**Comment by exussum12** [comment]
Can you confirm this file doesn't exist 

ls -l /usr/lib/ssl/certs

Thanks

**Comment by wa1kb0y** [comment]
```
user@server:~/$ ls -l /usr/lib/ssl/certs
lrwxrwxrwx 1 root root 14 May 19  2017 /usr/lib/ssl/certs -> /etc/ssl/certs
```

**Comment by exussum12** [comment]
Yeah same thing :( Ok looks like that confirms the info from `openssl_get_cert_locations` can't be trusted to give a correct path.

So #48 removes it. The CA Dir works fine, but capath needs to be set to a valid PEM cert for it to fall back to using the cadir from testing it. 

Can test from command line like so

```strace -f  curl -vvv --cacert /tmp/certs/DigiCert_Global_Root_CA.pem --capath /tmp/certs https://google.com/ 2>&1 | grep open```

Googles root CA is global sign, which is picked up correctly from the `--capath` , to make it to there though `cacert` needs to be a correct file.

**Comment by Seldaek** [comment]
v1.2.3 is out with the latest fix which removes openssl_get_cert_locations() completely.. hopefully back to normal for everyone.

**Comment by smatyas** [comment]
We had a similar issue on debian

```
cURL error (77): error setting certificate verify locations:
  CAfile: /usr/lib/ssl/certs
  CApath: /etc/ssl/certs
```

And I can confirm, that **v1.2.3 fixed it for us.**

Thank you all! :)
